language: node_js
node_js: '10'
jobs:
  include:
    - stage: Create release
      if: branch = master
      name: Semantic release
      os: linux
      dist: xenial
      node_js: lts/*
      script: skip
      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: true
        script: npx semantic-release

    - stage: Build stage
      if: tag IS present
      name: "Build on Linux"
      os: linux
      dist: xenial
      script:
        - yarn run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: true
        local_dir: dist
        on:
          tags: true
cache:
  directories:
  - node_modules
