name: Build Electron

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  ELECTRON_CACHE: $HOME/.cache/electron
  ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
  USE_HARD_LINKS: false
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      YARN_GPG: no
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Windows
        run: yarn run build:win

  build-macOS:
    name: Build macOS
    runs-on: macos-latest
    environment: build
    env:
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build macOS
        run: yarn run build:mac

  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build ubuntu
        run: yarn run build:linux
